spring:
  datasource:
    url: jdbc:h2:mem:testdb  # Используем H2 базу данных для тестирования
    driver-class-name: org.h2.Driver
    username: sa
    password: password
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: false
  flyway:
    enabled: false  # Отключаем миграции Flyway на этапе сборки
